### Get semua user
# GET http://localhost:3000/users
GET https://backend-production-e645.up.railway.app/users
Content-Type: application/json

### Get user by id
GET http://localhost:3000/users/1
Content-Type: application/json

### POST create user
# POST http://localhost:3000/users
POST https://backend-production-e645.up.railway.app/users
Content-Type: application/json

{
    "name": "Ardiyanto Putra",
    "email": "Ardiy@example.com",
    "gender": "male"
}
### POST UPDATE user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "John FIKRI",
    "email": "JHON@example.com",
    "gender": "male"
}
### POST DELETE user
DELETE http://localhost:3000/users/2
Content-Type: application/json